name: Expresiones
run-name: learning-expressions
on:
  workflow_dispatch:
    inputs:
      edad:
        description: 'Edad'
        required: true
        type: integer
      nombre:
        description: 'Name'
        required: true
        default: 'Hever'
        type: string
jobs:
  mayor: 
    if: ${{ inputs.edad >= 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: Correr Script
        run: echo ${{ inputs.nombre }} es mayor de edad
  menor:
    if: ${{ inputs.edad < 18 }}
      runs-on: ubuntu-latest
      steps:
        - name: Correr Script
          run: echo ${{ inputs.nombre }} es menor de edad
      